require('./anonUrl404');
require('./editorReset');
require('./enterPostPassword');
require('./createComponentHeading');
require('./createComponentImage');
require('./createComponentParagraph');
require('./login');
require('./logout');
require('./mediaLibraryAdd');
require('./mediaLibrarySelect');
require('./mediaLibraryUpload');
require('./publish');
require('./save')
require('./saveDraft')
require('./selectComponent');
require('./setFeaturedImage');
require('./setTitle');
require('./setVisibility');
require('./update');
require('./visitEditPage');
require('./wp');
